resources:
  - resources/namespace.yaml

namespace: &namespace kube-state-metrics

helmCharts:
  - name: kube-state-metrics
    repo: https://prometheus-community.github.io/helm-charts
    version: 6.4.2
    releaseName: kube-state-metrics
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true
