resources:
  - resources/vso.yaml
  - resources/vso-secrets.yaml

namespace: &namespace prometheus-exporter

helmGlobals:
  chartHome: ../../charts/

helmCharts:
  - name: tailscale-exporter
    releaseName: prometheus-exporter-tailscale
    namespace: *namespace
    valuesFile: values.yaml
