namespace: traefik-external

helmGlobals:
  chartHome: ../../charts/

helmCharts:
  - name: traefik-external-services
    releaseName: traefik-external
    namespace: traefik-external
    valuesFile: values.yaml
