apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`portainer.vrsf.in`)
      kind: Rule
      services:
        - name: portainer
          port: 9000
  tls:
    certResolver: letsencrypt
