---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oidc-config
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: dependency-track/secrets/oidc-config
  refreshAfter: 30s
  destination:
    create: true
    name: oidc-config
    transformation:
      excludeRaw: true
  rolloutRestartTargets:
    - name: dependency-track-api-server
      kind: StatefulSet
    - name: dependency-track-frontend
      kind: Deployment
