---
apiVersion: v1
kind: Endpoints
metadata:
  name: ext-home-assistant
subsets:
  - addresses:
      - ip: 10.0.103.11
    ports:
      - name: http
        port: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: ext-home-assistant
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8123
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ext-home-assistant
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ha.vrsf.in`)
      kind: Rule
      services:
        - name: ext-home-assistant
          port: 80
  tls:
    certResolver: letsencrypt
