---
apiVersion: v1
kind: Endpoints
metadata:
  name: ext-jellyfin-lxc
subsets:
  - addresses:
      - ip: 10.0.103.14
    ports:
      - name: http
        port: 8096
---
apiVersion: v1
kind: Service
metadata:
  name: ext-jellyfin-lxc
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8096
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ext-jellyfin-lxc
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyfin-lxc.vrsf.in`)
      kind: Rule
      services:
        - name: ext-jellyfin-lxc
          port: 80
  tls:
    certResolver: letsencrypt
