namespace: &namespace prometheus-exporter

helmCharts:
  - name: prometheus-blackbox-exporter
    repo: https://prometheus-community.github.io/helm-charts
    version: 11.6.1 # https://github.com/prometheus-community/helm-charts/releases?q=%22prometheus-blackbox-exporter%22&expanded=true
    releaseName: prometheus-exporter-blackbox
    namespace: *namespace
    valuesFile: values.yaml
    includeCRDs: true
    apiVersions:
      - policy/v1/PodDisruptionBudget
