---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: oauth-config
spec:
  vaultAuthRef: vso-auth
  mount: services
  type: kv-v2
  path: prometheus-exporter-tailscale/secrets/oauth
  refreshAfter: 30s
  destination:
    name: oauth-config
    create: true
  rolloutRestartTargets:
    - name: prometheus-tailscale-exporter
      kind: Deployment
