namespace: &ns argo-system

resources:
  - resources/namespace.yaml
  - resources/ingress-route.yaml
  - resources/vso.yaml
  - resources/vso-secrets.yaml

helmCharts:
  - name: argo-cd
    releaseName: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 9.1.9 # helm/argo-cd
    namespace: *ns
    valuesFile: values.yaml
    additionalValuesFiles:
      - notifications.values.yaml
    includeCRDs: true
    apiVersions:
      - monitoring.coreos.com/v1
